"""
VigiRail — Static fleet dataset.

Real Indian Railways services with their routes, zones and station lists.
This module is the single source of truth for `/api/trains`; a production
deployment would replace it with a call to the NTES / railway planning API.
"""

from __future__ import annotations

FLEET: dict[str, dict] = {
    "12951": {
        "number": "12951",
        "name": "Mumbai Rajdhani Express",
        "zone": "Western Railway",
        "zone_code": "WR",
        "type": "Rajdhani",
        "from": "Mumbai Central",
        "to": "New Delhi",
        "distance_km": 1384,
        "avg_speed_kmh": 88,
        "rake_type": "LHB",
        "route": [
            {"code": "MMCT", "name": "Mumbai Central", "km": 0, "state": "Maharashtra"},
            {"code": "BRC", "name": "Vadodara Jn", "km": 391, "state": "Gujarat"},
            {"code": "RTM", "name": "Ratlam Jn", "km": 528, "state": "Madhya Pradesh"},
            {"code": "KTB", "name": "Kota Jn", "km": 755, "state": "Rajasthan"},
            {"code": "SWM", "name": "Sawai Madhopur", "km": 844, "state": "Rajasthan"},
            {"code": "NDLS", "name": "New Delhi", "km": 1384, "state": "Delhi"},
        ],
    },
    "12301": {
        "number": "12301",
        "name": "Howrah Rajdhani Express",
        "zone": "Eastern Railway",
        "zone_code": "ER",
        "type": "Rajdhani",
        "from": "Howrah Jn",
        "to": "New Delhi",
        "distance_km": 1441,
        "avg_speed_kmh": 85,
        "rake_type": "LHB",
        "route": [
            {"code": "HWH", "name": "Howrah Jn", "km": 0, "state": "West Bengal"},
            {"code": "DKAE", "name": "Dankuni", "km": 18, "state": "West Bengal"},
            {"code": "ASN", "name": "Asansol Jn", "km": 200, "state": "West Bengal"},
            {"code": "GAYA", "name": "Gaya Jn", "km": 420, "state": "Bihar"},
            {"code": "PNBE", "name": "Patna Jn", "km": 531, "state": "Bihar"},
            {"code": "MGS", "name": "Mughal Sarai Jn", "km": 671, "state": "Uttar Pradesh"},
            {"code": "CNB", "name": "Kanpur Central", "km": 979, "state": "Uttar Pradesh"},
            {"code": "NDLS", "name": "New Delhi", "km": 1441, "state": "Delhi"},
        ],
    },
    "12002": {
        "number": "12002",
        "name": "Bhopal Shatabdi Express",
        "zone": "North Central Railway",
        "zone_code": "NCR",
        "type": "Shatabdi",
        "from": "Habibganj",
        "to": "New Delhi",
        "distance_km": 702,
        "avg_speed_kmh": 100,
        "rake_type": "LHB",
        "route": [
            {"code": "HBJ", "name": "Habibganj (Bhopal)", "km": 0, "state": "Madhya Pradesh"},
            {"code": "VID", "name": "Vidisha", "km": 55, "state": "Madhya Pradesh"},
            {"code": "BHS", "name": "Bina Jn", "km": 155, "state": "Madhya Pradesh"},
            {"code": "JHS", "name": "Jhansi Jn", "km": 311, "state": "Uttar Pradesh"},
            {"code": "GWL", "name": "Gwalior Jn", "km": 419, "state": "Madhya Pradesh"},
            {"code": "AGC", "name": "Agra Cantt", "km": 498, "state": "Uttar Pradesh"},
            {"code": "NDLS", "name": "New Delhi", "km": 702, "state": "Delhi"},
        ],
    },
    "22691": {
        "number": "22691",
        "name": "Bengaluru Rajdhani Express",
        "zone": "South Western Railway",
        "zone_code": "SWR",
        "type": "Rajdhani",
        "from": "Bengaluru Cantt",
        "to": "New Delhi",
        "distance_km": 2414,
        "avg_speed_kmh": 76,
        "rake_type": "LHB",
        "route": [
            {"code": "BNC", "name": "Bengaluru Cantt", "km": 0, "state": "Karnataka"},
            {"code": "KJM", "name": "Krishnarajapura", "km": 14, "state": "Karnataka"},
            {"code": "JTJ", "name": "Jolarpettai", "km": 147, "state": "Tamil Nadu"},
            {"code": "MAS", "name": "Chennai Central", "km": 359, "state": "Tamil Nadu"},
            {"code": "TPTY", "name": "Tirupati", "km": 462, "state": "Andhra Pradesh"},
            {"code": "BZA", "name": "Vijayawada Jn", "km": 733, "state": "Andhra Pradesh"},
            {"code": "NGP", "name": "Nagpur", "km": 1237, "state": "Maharashtra"},
            {"code": "BPL", "name": "Bhopal Jn", "km": 1837, "state": "Madhya Pradesh"},
            {"code": "JHS", "name": "Jhansi Jn", "km": 2031, "state": "Uttar Pradesh"},
            {"code": "NDLS", "name": "New Delhi", "km": 2414, "state": "Delhi"},
        ],
    },
    "12627": {
        "number": "12627",
        "name": "Karnataka Express",
        "zone": "South Western Railway",
        "zone_code": "SWR",
        "type": "Express",
        "from": "Bengaluru City Jn",
        "to": "New Delhi",
        "distance_km": 2406,
        "avg_speed_kmh": 66,
        "rake_type": "LHB",
        "route": [
            {"code": "SBC", "name": "Bengaluru City Jn", "km": 0, "state": "Karnataka"},
            {"code": "MYS", "name": "Mysuru Jn", "km": 143, "state": "Karnataka"},
            {"code": "KPN", "name": "Kuppam", "km": 254, "state": "Andhra Pradesh"},
            {"code": "MAS", "name": "Chennai Central", "km": 359, "state": "Tamil Nadu"},
            {"code": "NGP", "name": "Nagpur", "km": 1237, "state": "Maharashtra"},
            {"code": "BPL", "name": "Bhopal Jn", "km": 1837, "state": "Madhya Pradesh"},
            {"code": "JHS", "name": "Jhansi Jn", "km": 2031, "state": "Uttar Pradesh"},
            {"code": "NDLS", "name": "New Delhi", "km": 2406, "state": "Delhi"},
        ],
    },
    "20501": {
        "number": "20501",
        "name": "Tejas Express (NDLS–AGC)",
        "zone": "Northern Railway",
        "zone_code": "NR",
        "type": "Vande Bharat",
        "from": "New Delhi",
        "to": "Agra Cantt",
        "distance_km": 195,
        "avg_speed_kmh": 95,
        "rake_type": "Tejas LHB",
        "route": [
            {"code": "NDLS", "name": "New Delhi", "km": 0, "state": "Delhi"},
            {"code": "NZM", "name": "Hazrat Nizamuddin", "km": 18, "state": "Delhi"},
            {"code": "FDB", "name": "Faridabad", "km": 34, "state": "Haryana"},
            {"code": "KAL", "name": "Khalilabad", "km": 118, "state": "Uttar Pradesh"},
            {"code": "AGC", "name": "Agra Cantt", "km": 195, "state": "Uttar Pradesh"},
        ],
    },
    "12429": {
        "number": "12429",
        "name": "Lucknow Mail",
        "zone": "Northern Railway",
        "zone_code": "NR",
        "type": "Mail",
        "from": "New Delhi",
        "to": "Lucknow NR",
        "distance_km": 512,
        "avg_speed_kmh": 71,
        "rake_type": "LHB",
        "route": [
            {"code": "NDLS", "name": "New Delhi", "km": 0, "state": "Delhi"},
            {"code": "GZB", "name": "Ghaziabad", "km": 27, "state": "Uttar Pradesh"},
            {"code": "MB", "name": "Moradabad", "km": 167, "state": "Uttar Pradesh"},
            {"code": "BE", "name": "Bareilly Jn", "km": 252, "state": "Uttar Pradesh"},
            {"code": "SHC", "name": "Shahjahanpur", "km": 330, "state": "Uttar Pradesh"},
            {"code": "HRI", "name": "Hardoi", "km": 405, "state": "Uttar Pradesh"},
            {"code": "LKO", "name": "Lucknow NR", "km": 512, "state": "Uttar Pradesh"},
        ],
    },
}


def get_train(train_number: str) -> dict | None:
    return FLEET.get(train_number)
