/**
 * MaintenanceCard.jsx
 * Maintenance suggestions generated by ML model.
 *
 * ACCESSIBILITY:
 * - Plain English action titles ("STOP TRAIN" not "Emergency Alert")
 * - Color-coded urgency badges
 * - Large enough text for elderly users
 */
import React from 'react';

const URGENCY = {
  urgent:  { bg: 'var(--red-bg)',    color: 'var(--red)',    label: 'URGENT' },
  today:   { bg: 'var(--red-bg)',    color: 'var(--red)',    label: 'Today'  },
  soon:    { bg: 'var(--yellow-bg)', color: 'var(--yellow)', label: 'Soon'   },
  planned: { bg: 'var(--blue-bg)',   color: 'var(--blue)',   label: 'Planned'},
  done:    { bg: 'var(--green-bg)',  color: 'var(--green)',  label: 'Done'   },
};

function MaintItem({ item }) {
  const u = URGENCY[item.urgency] || URGENCY.planned;
  return (
    <div style={{
      display: 'flex', gap: 14, alignItems: 'flex-start',
      padding: '12px 0', borderBottom: '1px solid var(--border)',
    }}>
      <div style={{
        width: 36, height: 36, borderRadius: 8,
        background: u.bg, display: 'flex',
        alignItems: 'center', justifyContent: 'center',
        fontSize: 18, flexShrink: 0,
      }}>
        {item.icon}
      </div>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 15, fontWeight: 500, marginBottom: 3 }}>{item.title}</div>
        <div style={{ fontSize: 13, color: 'var(--muted)' }}>{item.detail}</div>
      </div>
      <div style={{
        padding: '3px 10px', borderRadius: 20,
        fontSize: 12, fontWeight: 500,
        background: u.bg, color: u.color,
        whiteSpace: 'nowrap', flexShrink: 0,
        alignSelf: 'flex-start', marginTop: 2,
      }}>
        {u.label}
      </div>
    </div>
  );
}

export function MaintenanceCard({ suggestions }) {
  return (
    <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 14, padding: 20 }}>
      <div style={titleStyle}>🔧 Maintenance Actions Needed</div>
      {(suggestions || []).map((s, i) => <MaintItem key={i} item={s} />)}
    </div>
  );
}

/**
 * EventLog.jsx
 * Scrollable log of all system events.
 */
export function EventLog({ events }) {
  return (
    <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 14, padding: 20 }}>
      <div style={titleStyle}>📋 Recent Events Log</div>
      <div style={{ maxHeight: 220, overflowY: 'auto' }}>
        {(events || []).map((e, i) => (
          <div key={i} style={{
            fontSize: 13, color: 'var(--muted)',
            padding: '6px 0',
            borderBottom: '1px solid rgba(99,160,255,0.06)',
            display: 'flex', gap: 10,
          }}>
            <span style={{ fontFamily: 'Courier New, monospace', color: 'rgba(99,160,255,0.5)', flexShrink: 0 }}>
              {e.time}
            </span>
            <span style={{ flex: 1 }}>{e.text}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

const titleStyle = {
  fontFamily: 'var(--font-head)',
  fontSize: 14, fontWeight: 600,
  textTransform: 'uppercase',
  letterSpacing: '0.08em',
  color: 'var(--muted)',
  marginBottom: 14,
};
