"""
VigiRail — Inspection reports.

GET /api/reports/inspection?train=…&format=csv|json   (Admin / Inspector)

Generates a real, downloadable inspection report from the current telemetry
snapshot.  CSV opens directly in Excel / Google Sheets; JSON is intended for
downstream integrations.  Report generation is read-only — it never mutates
live simulation state.
"""

from __future__ import annotations

import csv
import io
from datetime import UTC, datetime
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status

from app.core.deps import AuthUser, require_roles
from app.core.users import ROLE_ADMIN, ROLE_INSPECTOR
from app.models.schemas import ReportMeta
from app.services.state import app_state
from app.services.telemetry import capture_snapshot

router = APIRouter(prefix="/api/reports", tags=["reports"])

_RISK_BANDS = [
    ("Vibration", "mm/s", 5.0, 8.0),
    ("Bearing temperature", "°C", 70.0, 90.0),
    ("Acoustic level", "dB", 60.0, 80.0),
    ("Component wear", "%", 50.0, 75.0),
]


def _report_id(now: datetime) -> str:
    return f"VR-{now:%Y%m%d}-{now:%H%M%S}"


def _build_report(train_number: str, username: str) -> dict:
    now = datetime.now(UTC)
    snapshot = capture_snapshot(
        train_number, record=False, logged_user=username, user_role="report"
    )
    _, recent = app_state.history_page(limit=10, offset=0, train=train_number)
    return {
        "report_id": _report_id(now),
        "generated_at": now.isoformat(),
        "generated_by": username,
        "train": snapshot.train.model_dump(by_alias=True),
        "train_id": snapshot.train_id,
        "route_progress": {
            "current_station": snapshot.current_station.model_dump(),
            "stops_completed": sum(1 for r in snapshot.route if r.status == "past"),
            "stops_total": len(snapshot.route),
        },
        "state": snapshot.state.value,
        "health_score": snapshot.health_score,
        "failure_probability": snapshot.failure_probability,
        "model_confidence": snapshot.model_confidence,
        "sensors": snapshot.sensors.model_dump(),
        "bogies": [b.model_dump() for b in snapshot.bogies],
        "component_risks": snapshot.predictions.model_dump(),
        "maintenance": [m.model_dump() for m in snapshot.maintenance],
        "recent_history": recent,
    }


def _to_csv(report: dict) -> str:
    """Render the report as a sectioned CSV workbook-friendly string."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    train = report["train"]

    writer.writerow(["VigiRail Inspection Report"])
    writer.writerow(["Report ID", report["report_id"]])
    writer.writerow(["Generated at (UTC)", report["generated_at"]])
    writer.writerow(["Generated by", report["generated_by"]])
    writer.writerow([])
    writer.writerow(["Train", f"{report['train_id']} — {train['name']}"])
    writer.writerow(["Route", f"{train['from']} → {train['to']}"])
    writer.writerow(["Zone", f"{train['zone']} ({train['zone_code']})"])
    writer.writerow(["Rake", train["rake_type"]])
    writer.writerow(["Stops completed", f"{report['route_progress']['stops_completed']}/{report['route_progress']['stops_total']}"])
    writer.writerow(["Overall state", report["state"].upper()])
    writer.writerow(["Health score", f"{report['health_score']}%"])
    writer.writerow(["Failure probability", f"{report['failure_probability']}%"])
    writer.writerow(["Model confidence", f"{report['model_confidence']}%"])
    writer.writerow([])

    writer.writerow(["Sensor readings"])
    writer.writerow(["Parameter", "Value", "Unit", "Advisory", "Critical"])
    values = report["sensors"]
    for (label, unit, warn, danger), key in zip(
        _RISK_BANDS, ("vibration", "temperature", "acoustic", "wear"), strict=True
    ):
        writer.writerow([label, values[key], unit, warn, danger])
    writer.writerow([])

    writer.writerow(["Bogie status"])
    writer.writerow(["ID", "Label", "Status", "Bearing temp (°C)"])
    for bogie in report["bogies"]:
        writer.writerow([bogie["id"], bogie["label"], bogie["status"], bogie["temp"]])
    writer.writerow([])

    writer.writerow(["Component risk"])
    writer.writerow(["Component", "Risk (%)"])
    for name, value in report["component_risks"].items():
        writer.writerow([name.replace("_", " ").title(), value])
    writer.writerow([])

    writer.writerow(["Maintenance actions"])
    writer.writerow(["Priority", "Action", "Detail"])
    for item in report["maintenance"]:
        writer.writerow([item["urgency"], item["title"], item["detail"]])
    writer.writerow([])

    writer.writerow(["Recent readings (newest first)"])
    writer.writerow(["Timestamp", "State", "Vibration", "Temperature", "Acoustic", "Wear", "Risk %"])
    for row in report["recent_history"]:
        writer.writerow([
            row["timestamp"], row["state"], row["vibration"], row["temperature"],
            row["acoustic"], row["wear"], row["risk_pct"],
        ])

    return buf.getvalue()


@router.get("/inspection")
def inspection_report(
    train: str = Query(..., description="Train number"),
    format: Literal["csv", "json"] = Query("csv"),
    user: AuthUser = Depends(require_roles(ROLE_ADMIN, ROLE_INSPECTOR)),
):
    """Download an inspection report for one train (CSV or JSON)."""
    try:
        report = _build_report(train, user.username)
    except LookupError:
        raise HTTPException(
            status.HTTP_404_NOT_FOUND, f"Unknown train '{train}'"
        ) from None

    if format == "json":
        return report

    csv_text = _to_csv(report)
    filename = f"vigirail-inspection-{train}-{report['report_id']}.csv"
    return Response(
        content=csv_text,
        media_type="text/csv; charset=utf-8",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-Report-ID": report["report_id"],
        },
    )


@router.get("/latest-meta", response_model=ReportMeta)
def latest_meta(
    train: str = Query(...),
    user: AuthUser = Depends(require_roles(ROLE_ADMIN, ROLE_INSPECTOR)),
) -> ReportMeta:
    """Lightweight metadata for the most recently generated report id."""
    now = datetime.now(UTC)
    return ReportMeta(
        report_id=_report_id(now),
        generated_at=now,
        train_id=train,
        generated_by=user.username,
    )
